### ISSUE TITLE
Link predict in MKG task

### ISSUE THREAD

**Issue by liang-ry** [zjunlp/MKGformer#1]
Is it possible to predict tail entity T (h,r,?) only from the head entity H and relation R in MKG task? Is it possible to perform (? ,r,t) link prediction task? Since I did not see the specific description of the prediction header entity in detail in the paper, I really hope you can answer. Thank you!

**Comment by njcx-ai** [comment]
Thanks for your attention! 
1. I understand that you are asking whether our  model can predict tail entity T (h,r,?) only from the head entity H and relation R without pictures. If so, you can cut off the VIT model and only leverage the BERT-like model to conduct conventional link prediction tasks.
2. The experiments on link prediction tasks include  (?, r, t)  and (h, r, ?) , we just take (h, r, ?)  as example in the paper.  You can refer to the detailed operation in our code.
