### ISSUE TITLE
How can we run the MKG-main.py?

### ISSUE THREAD

**Issue by yasNing** [zjunlp/MKGformer#11]
Hi, I recently want to complete a MMKG in my own datasets. Specifically, I want to use your MKG code. However, I can't donwnload the image data for FB-15K-237 and WN18, I also can't run the main function in the MKG directory.
<img width="904" alt="1661908935894" src="https://user-images.githubusercontent.com/93892617/187572134-587e3353-c40b-456a-af3e-ba7776c3b66e.png">

Is there more information about how to download image data and where to store it? If we run your multi-modal knowledge graph, that will make it easier for me to reconstruct my own multi-modal entity-relationship dataset.

Thanks!!

**Comment by flow3rdown** [comment]
Hi, thanks for your attention!
You can download the image data of FB15k-237 from [mmkb](https://github.com/mniepert/mmkb) which provides a list of image URLs. Entity images in WN18 can be obtained from ImageNet, the specific steps can refer to [RSME](https://github.com/wangmengsd/RSME). And the downloaded image data can be stored in the `dataset` folder.

**Comment by yasNing** [comment]
Hi, thanks for your response! After I finished dataset construction, I catch anonther error information. I guess it is about the package versions, which is very to solve. Can you help provide more details about your code? This is the error information when I run the main.py in MKG.
![B`2LV{_4NB3` THPM4B3PVH](https://user-images.githubusercontent.com/93892617/187853280-c1750d8b-64ae-4df6-8b98-8f330936d92a.png)

**Comment by yasNing** [comment]
@Flow3rDown  I guess your package version could directly help me.

**Comment by flow3rdown** [comment]
Hi, you can find our environment requirements at [requirements.txt](https://github.com/zjunlp/MKGformer/blob/main/requirements.txt), hope it can help you.

**Comment by yasNing** [comment]
@Flow3rDown  I have installed my environment by that version, but there are still errors.

**Comment by flow3rdown** [comment]
Is there an error in the `--gpus` parameter? If you are running with a single gpu, you need to add a comma after the GPU id. For example, `--gpus 0,`

**Comment by yasNing** [comment]
Thanks a lot! I solve it.  I have another question that is "dev.txt" is your total triplets? What are the difference between "dev.txt" and "8shot-42-train.tsv"?

**Comment by flow3rdown** [comment]
`dev.tsv` is the validation data. The total triples should also include `train.tsv` and `test.tsv` data. `8shot-42-train.tsv` is the data which sample 8 instances per relation from `train.tsv`.

**Comment by yasNing** [comment]
However, I still don't know Multi - modal image data naming format. For example,  if a entity is "/m/0wh3",  its corresponding image data should be stored in folder FB15k-images like this?
![)F2UESEUO2_I%B4Q@B8S7QN](https://user-images.githubusercontent.com/93892617/187895565-181ae55a-856b-4d52-85e4-d577d6e02ace.png)

**Comment by yasNing** [comment]
However, I still don't know Multi - modal image data naming format. For example, if a entity is "/m/0wh3", its corresponding image data should be stored in folder FB15k-images like this?
![Uploading PD$L%OP{0MX~NP81N7NEZ@R.png…]()

**Comment by yasNing** [comment]
@Flow3rDown  
However, I still don't know Multi - modal image data naming format. For example, if a entity is "/m/0wh3", its corresponding image data should be stored in folder FB15k-images like this?
![图片1](https://user-images.githubusercontent.com/93892617/187898569-cba4307a-77e8-4533-962a-89d74243d81c.png)

**Comment by flow3rdown** [comment]
Yes, you're right.
