### ISSUE TITLE
ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'

### ISSUE THREAD

**Issue by VinsonZhangS** [zjunlp/MKGformer#12]
您好，我按照requirements.txt进行安装环境后遇到以下几个主要问题：
在Python3.8环境中：
1.dataclasses没有0.8版本，只有0.6版本，Pypi中说是因为在Python3.8中已经被整合到Python中了。
我选择安装dataclasses==0.6
2.torchvision与torch版本不匹配，torchvision==0.8.2只匹配torch==1.7.1
我选择安装torch1.7.1
3.ImportError: cannot import name 'get_num_classes' from 'torchmetrics.utilities.data'
这个可能与我安装中自作主张有关
但是如果选择的是python3.6环境的话，安装的scikit-learn版本无法超过1.0
请问以上问题您当时有没有遇到过，请问您能不能提供一些解决办法？

**Comment by flow3rdown** [comment]
请问您的pytorch_lightning的版本是多少？

**Comment by VinsonZhangS** [comment]
1.3.1
除上述版本出现部分调整外，其他的包都是严格按照requirements,txt文件来安装的

**Comment by flow3rdown** [comment]
是不是你的torchmetrics版本太高了，torchmetrics在0.8.0后删除了get_num_classes，torchmetrics==0.7.3是可以正常运行的。

**Comment by VinsonZhangS** [comment]
抱歉这么久才回复，已经按照您的方法解决了这个问题，非常感谢！
