### ISSUE TITLE
关于Ｍ-encoder中的一些实现细节

### ISSUE THREAD

**Issue by shengyenlin** [zjunlp/MKGformer#13]
您好，

关于M-Encoder中PGI以及CAF的代码储存在哪一个py档呢？

TODO的意思是否需要自己手刻实现？

能否请您开恩提供，下礼拜有一个紧急的会议，求求您了。

**Comment by flow3rdown** [comment]
PGI和CAF的代码在[modeling_unimo.py](https://github.com/zjunlp/MKGformer/blob/main/MKG/models/modeling_unimo.py)文件中，PGI的实现位于[252-254](https://github.com/zjunlp/MKGformer/blob/9a3321c0e6808af29dfab78d46220315f473475c/MKG/models/modeling_unimo.py#L252)行，CAF的实现位于[BertFusion](https://github.com/zjunlp/MKGformer/blob/9a3321c0e6808af29dfab78d46220315f473475c/MKG/models/modeling_unimo.py#L397)中。
TODO不需要自己手动实现，只是注释

**Comment by shengyenlin** [comment]
了解,非常感谢您的迅速回覆,在trace code时太不小心...

再请教整个模型的细节理解有无错误。
这篇论文的精神是把BERT的12层layer以及ViT的12层layer中的后三层拿出来做PGI以及CAF，以达到良好的训练结果，不晓得有无理解上的错误。

**Comment by flow3rdown** [comment]
> 了解,非常感谢您的迅速回覆,在trace code时太不小心...
> 
> 再请教整个模型的细节理解有无错误。 这篇论文的精神是把BERT的12层layer以及ViT的12层layer中的后三层拿出来做PGI以及CAF，以达到良好的训练结果，不晓得有无理解上的错误。

是这样的

**Comment by shengyenlin** [comment]
了解，感谢您
