### ISSUE TITLE
加载预训练模型时报错

### ISSUE THREAD

**Issue by Maigewm** [zjunlp/MKGformer#14]
我在加载MKG预训练模型时反复报如下错误：
pytorch_lightning.utilities.exceptions.MisconfigurationException: CUDAAccelerator can not run on your system since the accelerator is not available. The following accelerator(s) is available and can be passed into `accelerator` argument of `Trainer`: ['cpu'].
但是我的本机是有CUDA和GPU的，请问有没有遇到同样问题的朋友？求解答！
谢谢！

**Comment by zxlzr** [comment]
您好建议您安装虚拟环境和正确的python包重试一下，这个可能是pytorch_lightning版本不正确

**Comment by Maigewm** [comment]
多谢，已解决，是由于pytorch、cuda和pytorch_lightning 的版本不匹配问题。
