### ISSUE TITLE
mkg训练流程问题

### ISSUE THREAD

**Issue by vandarkfan** [zjunlp/MKGformer#15]
按照readme中显示流程，对fb15k-237预训练(pretrain_fb15k-237-image.sh)，在第五个epoch就达到了hit@1=0.99，用此模型进行训练(fb15k-237-image.sh)，得到的结果hit10为0.504，请问是否是我的训练参数没有调整正确呢，或者是训练过程不对呢

**Comment by flow3rdown** [comment]
您好，建议fb15k-237预训练可以多训几轮取最优模型再进行训练，如果结果差距还是很大，可以尝试使用不同的学习率，batch size建议与脚本中保持一致。

**Comment by njcx-ai** [comment]
您好，我们多次跑了实验，目前定位发现我们本地fb15k237-IMG的图片处理代码有个bug（github上的代码和其他数据预处理检查过了没问题），之前在处理fb15k237-IMG时候误把部分tail 和head 的部分重合数据传进去了，目前我们没调参跑出的结果是hit@1 0.256 hit@3 0.367 hit@10 0.504 MR 221 仍然是比多模态方法基线高的，fb15k237-IMG checkpoints见如下链接：https://drive.google.com/drive/folders/1NsLA7mXaVnhlYNvzRDWIcBxq2CpKF_6m?usp=share_link，
其中用有bug的代码跑的old模型，bug 修复跑的是new模型，目前git上代码也是新的（本地当时没注意到bug)。很感谢您间接帮我们发现了这个bug，给您带来了不便非常抱歉， 我们正在更新arxiv和正在申请更新proceeding。
