### ISSUE TITLE
关于FB15K-237-IMG数据集结果复现问题 (图片数据预处理bug已更正)

### ISSUE THREAD

**Issue by YuyingShang** [zjunlp/MKGformer#16]
作者您好，我认为您的工作做的非常有意义，所以最近在利用您所给出的FB15k-237和其IMG数据集进行论文实验结果的复现，lr和batzhsize均按照脚本文件给出的值设定，但是实验结果并不理想，和论文给出的值差别较大。想请问一下如何才能获得论文中的实验结果，谢谢。
![微信图片_20221028104428](https://user-images.githubusercontent.com/53067922/198477322-54b3c1db-eafb-4a47-91d3-24a1c6645af5.jpg)

**Comment by zxlzr** [comment]
您好，感谢您对我们工作的关注，可能是超参数或环境问题，我们这几天会重新检查下脚本和环境设置等检查好回复您，您可以加下二作同学wechat flow3r-D 详聊

**Comment by YuyingShang** [comment]
好的谢谢

**Comment by VinsonZhangS** [comment]
您好，请问您大概什么时候能够反馈一下最新进展，我在同样的实验中即使进行调参也没有办法将值跑至最好

**Comment by zxlzr** [comment]
> 

您好，我们已经定位到本地代码的Fb15K-237-IMG数据预处理时候有个bug，给您带来不便非常抱歉，今天会更新

**Comment by njcx-ai** [comment]
您好，我们多次跑了实验，目前定位发现我们本地fb15k237-IMG的图片处理代码有个bug（github上的代码和其他数据预处理检查过了没问题），之前在处理fb15k237-IMG时候误把部分tail 和head 的部分重合数据传进去了，目前我们没调参跑出的结果是hit@1 0.256 hit@3 0.367 hit@10 0.504 MR 221 仍然是比多模态方法基线高的，fb15k237-IMG checkpoints见如下链接：https://drive.google.com/drive/folders/1NsLA7mXaVnhlYNvzRDWIcBxq2CpKF_6m?usp=share_link, 其中用有bug的代码跑的old模型，bug 修复跑的是new模型，目前git上代码也是新的（本地当时没注意到bug)。很感谢您间接帮我们发现了这个bug，给您带来了不便非常抱歉， 我们正在更新arxiv和正在申请更新proceeding。

**Comment by zxlzr** [comment]
> 

FB15K-237-IMG图片数据预处理代码上有个严重bug，本地代码当时没发现这个bug，git上代码没问题是后期整理过的用的不同函数，给您带来麻烦了非常抱歉。

**Comment by hutao-boop** [comment]
> 您好，感谢您对我们工作的关注，可能是超参数或环境问题，我们这几天会重新检查下脚本和环境设置等检查好回复您，您可以加下二作同学wechat flow3r-D 详聊

你好，我也在复现这篇论文的实验，数据出了些问题，想加微信问问相关问题，但是这个微信号貌似搜不到，请问可以重新发一下吗

**Comment by liuyunjie3** [comment]
作者您好我按照您给的网盘下载的数据集，发现很多实体都确实对应的图片，这种情况正常吗？

<img width="1043" height="317" alt="Image" src="https://github.com/user-attachments/assets/c592f5bc-ed3c-4144-b72a-44b20e2e25f5" />
