### ISSUE TITLE
network disk links password

### ISSUE THREAD

**Issue by ninjaX2o** [zjunlp/MKGformer#20]
Thanks for your graceful code! I noticed that u have released network disk links for multimodal KG data，but I have no access to the password，could u tell me that? Thanks~

**Comment by zxlzr** [comment]
We provide additional network disk links for **multimodal KG data [link](https://pan.baidu.com/s/1TVArQSLmPjr2FsC8NkSiOA) with extraction code:ilbd**.

**Comment by wxxw-blip** [comment]
BUT it need the cipher

**Comment by flow3rdown** [comment]
> BUT it need the cipher

The password is `ilbd`

**Comment by ninjaX2o** [comment]
OH,I missed that，THANKS
