### ISSUE TITLE
关于代码中的TransformerLitModel类的问题

### ISSUE THREAD

**Issue by vandarkfan** [zjunlp/MKGformer#22]
您好，请问TransformerLitModel类中的training_step方法，labels和label分别表示什么意思呢？两者名称太相似，有点难理解。

**Comment by flow3rdown** [comment]
您好，`labels`是采用bce进行分类的时候的标签，`label`是采用ce分类时候的标签，产生过程位于[processor.py](https://github.com/zjunlp/MKGformer/blob/2c82145fb6af2070c95d450f8536db1d9378a0d4/MKG/data/processor.py#L100-L107)

**Comment by vandarkfan** [comment]
您好，非常感谢之前的回答，可以加个微信聊一下吗，代码里面关于预训练的部分有点难看懂，之前看别的代码里面的预训练都是直接调用，看到您的代码把参数加载到自己创建的模型里有点迷茫😭

**Comment by Flow3rDown** [comment]
> 您好，非常感谢之前的回答，可以加个微信聊一下吗，代码里面关于预训练的部分有点难看懂，之前看别的代码里面的预训练都是直接调用，看到您的代码把参数加载到自己创建的模型里有点迷茫😭

好的，我的微信是flow3r-D
