### ISSUE TITLE
No images in dataset 

### ISSUE THREAD

**Issue by mayanku** [zjunlp/MKGformer#24]
The folder FB15K-images and wn-18 images in the path [MKGformer]/dataset/   contain no images. Can you please provide the image data

**Comment by zxlzr** [comment]
Sorry, you can download from this link https://pan.baidu.com/share/init?surl=TVArQSLmPjr2FsC8NkSiOA  with the code ilbd.  We will provide a google drive link soon.

**Comment by zxlzr** [comment]
You can also download images from https://drive.google.com/file/d/197c4fCLVC6F7sCBqZIDwm5tjWeGJnZ5-/view?usp=share_link.
