### ISSUE TITLE
Error in torch vision version

### ISSUE THREAD

**Issue by mayanku** [zjunlp/MKGformer#25]
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.2 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.10.0, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1)
ERROR: No matching distribution found for torchvision==0.8.2

I am getting this error while installing torchvision==0.8.2 which version I should use to run this code

**Comment by flow3rdown** [comment]
Maybe you can try `pip install torchvision==0.8.0`

**Comment by mayanku** [comment]
ERROR: Could not find a version that satisfies the requirement torchvision==0.8.0 (from versions: 0.1.6, 0.1.7, 0.1.8, 0.1.9, 0.2.0, 0.2.1, 0.2.2, 0.2.2.post2, 0.2.2.post3, 0.10.0, 0.11.2, 0.11.3, 0.12.0, 0.13.0, 0.13.1, 0.14.0, 0.14.1)
ERROR: No matching distribution found for torchvision==0.8.0

**Comment by flow3rdown** [comment]
This maybe a problem caused by pip, refer to [stackoverflow](https://stackoverflow.com/questions/32302379/could-not-find-a-version-that-satisfies-the-requirement-package). You can also try to install the `.whl` file of [torchvision](https://pypi.org/project/torchvision/0.8.0/#files) directly.
