### ISSUE TITLE
no package named models.unimo_model

### ISSUE THREAD

**Issue by mayanku** [zjunlp/MKGformer#27]
from models.unimo_model import UnimoCRFModel
I am getting no module named models.unimo_model from where do I install this package and which package it is

**Comment by flow3rdown** [comment]
The `UnimoCRFModel` is defined at [MNER/models/unimo_model.py](https://github.com/zjunlp/MKGformer/blob/f118f43e60918f0806d765a4abfdb1db7548583a/MNER/models/unimo_model.py#L9)  and does not need to be installed.
I assume you are running the MNER experiment. I just ran the experiment with the following script and no errors occurred.
```bash
cd MNER
bash run_mner.sh
```

**Comment by mayanku** [comment]
In the end I got an RuntimeError: found no NVIDIA driver on your system. Is it necessary to have NVIDIA driver to run this code. Can I run it on CPU

**Comment by flow3rdown** [comment]
In the MNER experiment, you can run the program on CPU by adding `--device='cpu'` in `run_mner.sh`. 
However, we have been training the model on GPU, if something goes wrong, we will be glad to help you out.

**Comment by Cameliasss** [comment]
Could you please tell me how to solve the problem ModuleNotFoundError: No module named 'models.unimo_model'
