### ISSUE TITLE
wn18-img

### ISSUE THREAD

**Issue by ninjaX2o** [zjunlp/MKGformer#28]
您好，我从提供的Google Drive中下载了wn18-images，发现只有7,801个实体有图片文件夹，不知道是不是没有上传完整呢？

**Comment by flow3rdown** [comment]
您好，我们根据[RSME](https://github.com/wangmengsd/RSME)中WN18数据的获取方式去检索了图片，但有些实体并不能找到对应图片。

**Comment by ninjaX2o** [comment]
请问你们是怎么解决这个问题的呢？缺失实体图片对实验结果影响大吗

**Comment by flow3rdown** [comment]
有实体没有图片的话会进行padding，影响不大

**Comment by ninjaX2o** [comment]
好的 谢谢！

**Comment by ninjaX2o** [comment]
最后，麻烦问一下图片和文本的padding的代码在哪里？

**Comment by flow3rdown** [comment]
在这里https://github.com/zjunlp/MKGformer/blob/main/MKG/data/data_module.py

**Comment by ninjaX2o** [comment]
十分感谢！
