### ISSUE TITLE
您好，对于MRE部分的数据集有些问题想请教您一下

### ISSUE THREAD

**Issue by wisediag** [zjunlp/MKGformer#29]
粗略统计一下txt部分的：train.txt中有12247条数据，其中就有7751个None的无关系数据；test.txt中有1614条数据，其中就有974个None的无关系数据。大部分文本关系都是None，这样真的能学到实体关系信息吗？而且test的None数据也占到一半多，得到的分数是否不准确啊？

还要一点就是我发现子图中：RCNN抽取objects是比visual grounding抽取objects效果好一点，但他们的objects其实都没有准确抽到实体，大部分都只是重复一下原图的部分子图片。想问您一下这是什么情况啊？

**Comment by flow3rdown** [comment]
您好，MRE的数据来自于[MEGA](https://github.com/thecharm/Mega)，None表示两个实体之间无关系，在关系抽取中是比较常见的，数据集的作者也在这个[issue](https://github.com/thecharm/Mega/issues/3)中进行了说明。RCNN和visual grounding都是使用开源的框架进行抽取的，抽取的质量受制于框架的性能以及图文之间的相关性。此外，这个数据集中图片中大多是人物实体，一张图片中可抽取的实体数量有限，所以也会带来一些重复性问题。

**Comment by wisediag** [comment]
十分感谢大佬的回复！我还看了大佬的HVPNeT，还有大佬应该也参与的IFAformer，但对MRE任务还有一些小小的疑惑，想之后能请教您，大佬能加个联系方式么，十分感谢（我的微信：hwt1843791），辛苦大佬加一下啦！再次蟹蟹大佬

**Comment by zjutnlper** [comment]
> 十分感谢大佬的回复！我还看了大佬的HVPNeT，还有大佬应该也参与的IFAformer，但对MRE任务还有一些小小的疑惑，想之后能请教您，大佬能加个联系方式么，十分感谢（我的微信：hwt1843791），辛苦大佬加一下啦！再次蟹蟹大佬

大佬想加你，问些问题可以吗

**Comment by njcx-ai** [comment]
您好，可以加一下vx:  1158458395
