### ISSUE TITLE
你好，请问在多模态链接预测中，为什么论文输入序列和代码不一致

### ISSUE THREAD

**Issue by G-B-Y** [zjunlp/MKGformer#30]
https://github.com/zjunlp/MKGformer/blob/5c4d8c0e9238ba7d93ea16cf4633c71e7a52e04c/MKG/data/processor.py#L100-L107

**Comment by flow3rdown** [comment]
你好，请问你指的是[UNK]和[PAD] tokens吗，[UNK]会在输入之前被替换为对应的实体id，[PAD]会被替换为关系id。

**Comment by G-B-Y** [comment]
你好，总共有两点疑问：
1. 程序中加入关系描述，文章中没有
2. 尾实体预测时，头实体描述没有放在头实体ID后，与文中格式不符

**Comment by njcx-ai** [comment]
您好：
非常感谢您对我们的论文表示关注和提出疑问。

对于第一个问题，我们在论文的公式(3)中是包含关系r的，代码中用的是关系的名称（数据集所包含的内容），例如birth of place这样一个关系名称， 而不是对关系额外的文本描述或外部知识。这种在预训练语言模型做KGC的任务中是常规操作（如[1][2]），很抱歉我们在文章中的表述上可能会出现一些遗漏导致误解。

对于第二个问题，论文中和代码实现里头实体描述与头实体ID是都是挨着放在一起的，实验中头实体描述和头实体ID的前后顺序对实验结果几乎没影响，很感谢您指出这个问题。我们会进行进一步的核查和修正。

[1] KG-BERT: BERT for Knowledge Graph Completion.
[2] Structure-Augmented Text Representation Learning for Efficient Knowledge Graph Completion. WWW2021

再次感谢您的关注和指正。
