### ISSUE TITLE
MRE里面的数据文件在哪里

### ISSUE THREAD

**Issue by With-JS** [zjunlp/MKGformer#31]

**Comment by flow3rdown** [comment]
您可以通过[Google Drive](https://drive.google.com/file/d/1q5_5vnHJ8Hik1iLA9f5-6nstcvvntLrS/view?usp=sharing)下载，或者通过以下命令下载：
```bash
wget 120.27.214.45/Data/re/multimodal/data.tar.gz
tar -xzvf data.tar.gz
```
