### ISSUE TITLE
TransformerLitModel中的self.num_training_steps找不到

### ISSUE THREAD

**Issue by KiteYN** [zjunlp/MKGformer#34]
您好，运行MKG部分代码的时候找不到 self.num_training_steps, 请问这个 self.num_training_steps 在哪里定义的，谢谢百忙之中抽空解答~

File "/home/slyang/MKG/lit_models/transformer.py", line 157, in configure_optimizers
    scheduler = get_linear_schedule_with_warmup(optimizer, num_warmup_steps=self.num_training_steps * self.args.warm_up_radio, num_training_steps=self.num_training_steps)
  File "/home/slyang/.conda/envs/kg_env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1208, in __getattr__
    type(self).__name__, name))
AttributeError: 'TransformerLitModel' object has no attribute 'num_training_steps'

**Comment by flow3rdown** [comment]
`self.num_training_steps`是在[MKG/lit_models/base.py](https://github.com/zjunlp/MKGformer/blob/5c4d8c0e9238ba7d93ea16cf4633c71e7a52e04c/MKG/lit_models/base.py#LL75C40-L75C40)定义的，正常跑应该不会报错

**Comment by KiteYN** [comment]
你好！已收到你的邮件！谢谢！

**Comment by KiteYN** [comment]
> `self.num_training_steps`是在[MKG/lit_models/base.py](https://github.com/zjunlp/MKGformer/blob/5c4d8c0e9238ba7d93ea16cf4633c71e7a52e04c/MKG/lit_models/base.py#LL75C40-L75C40)定义的，正常跑应该不会报错

收到，应该是pytorch_lightning 版本的问题，谢谢 ！

**Comment by HanMinge** [comment]
借楼，请问，对于升级版本的pytorch_lightning，获取不到父类的num_training_steps方法。目前版本为1.9.0。请问有解决办法吗？

**Comment by njcx-ai** [comment]
可能是您新升级版本的pytorch_lightning中self.num_training_steps的命名有变化，感觉只能找找有没有类似的定义，或者降版本

**Comment by HanMinge** [comment]
> 可能是您新升级版本的pytorch_lightning中self.num_training_steps的命名有变化，感觉只能找找有没有类似的定义，或者降版本

非常感谢您的回答，虽然关于pytorch_lightning 1.3.0版本装不上的问题还没有办法，且高版本会出现各种bug。 但当我回退到了pytorch_lightning=1.2.4 代码就正常执行了。
