### ISSUE TITLE
FB15k-237-IMG released the checkpoints

### ISSUE THREAD

**Issue by YuyangWei** [zjunlp/MKGformer#35]
您好，我想要与您的方法进行对比。请问一下，这个checkpoints的预训练方法是什么？

**Comment by njcx-ai** [comment]
您好，“FB15k-237-IMG released the checkpoints”这里指的是基于masked entity prediction的方式学习多模态实体的向量表示，基于此checkpoints我们进行后续的link prediction任务的训练。

**Comment by YuyangWei** [comment]
非常感谢您的回答！我现在遇到一个问题：OSError: Unable to load weights from pytorch checkpoint file for 'bert-base-uncased' at '/root/.cache/huggingface/transformers/a8041bf617d7f94ea26d15e218abd04afc2004805632abc0ed2066aa16d50d04.faf6ea826ae9c5867d12b22257f9877e6b8367890837bd60f7c54a29633f7f2f'If you tried to load a PyTorch model from a TF 2.0 checkpoint, please set from_tf=True.
不知道您有没有遇到过，我的pytorch版本是1.7.1

**Comment by njcx-ai** [comment]
您好，这个问题我们之前确实没遇到过呢，感觉像是模型版本和torch版本不匹配

**Comment by YuyangWei** [comment]
谢谢您的回答。还有个问题想要请教一下：在执行Missing Entity Prediction时，是不是需要很长时间，我运行一个epoch需要20个小时。

**Comment by zxlzr** [comment]
您好，抱歉回复晚了，具体速度和时间和gpu型号有关。

**Comment by wzl0422** [comment]
> 谢谢您的回答。还有个问题想要请教一下：在执行Missing Entity Prediction时，是不是需要很长时间，我运行一个epoch需要20个小时。

你好 我也是需要很久，大概一个epoch一小时，你解决了吗？
我用的3090
