### ISSUE TITLE
How to use vision embedding?

### ISSUE THREAD

**Issue by xpy990807** [zjunlp/MKGformer#36]
请问作者，您的模型中的uniMomodel的vision hidden state是没有做任何处理的，这个vision hidden state里面包含的信息是否是可以和text hidden state替换的，与text hidden state是等价的，者两者使用起来没有什么区别；或者不能等价，是考虑将uniMomodel作为多模态知识图谱的编码器，可以在其他下游任务上面使用呢？

**Comment by njcx-ai** [comment]
您好, 感谢您的关注。vision hidden state是在M-Encoder模块中与text hidden state进行信息交互的，选择以文本侧的uniMomodel的输出作为知识embedding编码是因为文本更易与单个entity和relation对应且可以在其他下游任务上面使用。

**Comment by xpy990807** [comment]
> 您好, 感谢您的关注。vision hidden state是在M-Encoder模块中与text hidden state进行信息交互的，选择以文本侧的uniMomodel的输出作为知识embedding编码是因为文本更易与单个entity和relation对应且可以在其他下游任务上面使用。


理解了，非常感谢您的及时回复
