### ISSUE TITLE
关于训练阶段的疑问？

### ISSUE THREAD

**Issue by chengq1001** [zjunlp/MKGformer#37]
很抱歉打扰到你，可能我的基础有一些差，为什么训练要分为两阶段呢？

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注。这里link prediction 任务分两阶段主要是为了在第一阶段把实体的文本表示信息编码到entity和relation的embedding中， 第二步训练才是符合任务形式的训练。
