### ISSUE TITLE
from models.unimo_model import UnimoCRFModel

### ISSUE THREAD

**Issue by Cameliasss** [zjunlp/MKGformer#38]
Traceback (most recent call last):
  File "run.py", line 11, in <module>
    from models.unimo_model import UnimoCRFModel
ModuleNotFoundError: No module named 'models.unimo_model'
I understand that the `models.unimo_model` is located in the same-level folder as `run.py`, and you are still encountering the issue even after following the instructions in the readme file and adding the parent folder path using `sys.path.append`.

**Comment by flow3rdown** [comment]
I think you should run `run_mner.sh` under `MKGformer/MNER`

**Comment by zxlzr** [comment]
have you solved your issue?
