### ISSUE TITLE
下载不了clip-vit-base-patch32

### ISSUE THREAD

**Issue by suexin27** [zjunlp/MKGformer#39]
可以提供一下“openai/clip-vit-base-patch32"的下载链接吗？
我已经联网了，但不知道为何服务器下载不下来？
<img width="1089" alt="image" src="https://github.com/zjunlp/MKGformer/assets/104906350/d1c33d7c-f85a-41c4-b1ce-0746d9734af7">

**Comment by flow3rdown** [comment]
您可以在https://huggingface.co/openai/clip-vit-base-patch32 将模型下载到本地，之后修改`vit_name`为本地模型路径。

**Comment by suexin27** [comment]
thanks ！！

**Comment by RZJGUYS** [comment]
> thanks ！！

你好，能向您请教一下具体的操作步骤吗

**Comment by RZJGUYS** [comment]
> 谢谢 ！！

您好，打扰您一下，我十分想知道如何操作，如果您百忙之中能抽出时间来我将不胜感激，我的联系QQ为907959373，十分感谢
