### ISSUE TITLE
数据集中的实体和IMG中的实体对应不上

### ISSUE THREAD

**Issue by wyZhang016** [zjunlp/MKGformer#42]
作者，您好，最近做实验的时候用了gitHub给的网盘中提供的IMG数据集，但是发现实体数目对应不上，以WN18RR为例，实体的数目应该有**40943**个，但是WN18-IMG对应的文件夹只有**7801**个，请问是不是有的实体没有对应的图片，然后处理的时候需要过滤掉没有图片的实体呢，这样做有没有什么影响，期待您的回复，谢谢

**Comment by flow3rdown** [comment]
您好，我们参考[RSME](https://github.com/wangmengsd/RSME)中WN18数据的获取方式去检索的图片，但是有些实体无法找到对应的图片，因此对于缺失的图片我们进行了padding，参考issue #28

**Comment by wyZhang016** [comment]
好的，感谢您的回答
