### ISSUE TITLE
RobertaUseLabelWord

### ISSUE THREAD

**Issue by zz4567** [zjunlp/MKGformer#43]
AttributeError: module 'models' has no attribute 'RobertaUseLabelWord'

**Comment by njcx-ai** [comment]
Hello, thank you very much for your attention to this matter. Regarding the question you've raised, I would recommend checking whether it might be an issue with the Hugging Face version you are using.

**Comment by zz4567** [comment]
您好，
我是把Hugging Face中的模型下载到了电脑中，因为不下载下来的话显示找不到该模型。



---- Replied Message ----
| From | Xiang ***@***.***> |
| Date | 05/02/2024 22:43 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [zjunlp/MKGformer] RobertaUseLabelWord (Issue #43) |

Hello, thank you very much for your attention to this matter. Regarding the question you've raised, I would recommend checking whether it might be an issue with the Hugging Face version you are using.

**Comment by njcx-ai** [comment]
您好，如果不是模型问题的话，那很可能是涉及到Roberta的那个transformer包的版本问题。

**Comment by zxlzr** [comment]
请问您还有什么问题吗？
