### ISSUE TITLE
运行结果

### ISSUE THREAD

**Issue by zz4567** [zjunlp/MKGformer#44]
![b22136b1dbfa4b1a791575504f9c092](https://github.com/zjunlp/MKGformer/assets/132807986/a21ae540-b5b6-4860-86c3-a2c377edfdd1)
你好，请问这是哪里的问题

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注。您的这个问题似乎发生在代码具体执行之前，我网上搜了下原因仅供您参考：

在 Kubernetes 中，退出代码 139 是当容器从其主机节点上的操作系统接收到 SIGSEGV 信号时发生的事件。

在 Linux 和其他类 Unix 操作系统中，SIGSEGV 是一种强制终止信号，告诉进程关闭。 当操作系统检测到一个进程正在尝试访问不存在的系统内存或该进程缺乏访问权限时，通常会生成此信号。

**Comment by zxlzr** [comment]
请问您还有什么问题吗？
