### ISSUE TITLE
MKG部分实验结果

### ISSUE THREAD

**Issue by Eel-sir** [zjunlp/MKGformer#46]
![~ILH7%2~MI YJM{QWCJH0{Y](https://github.com/zjunlp/MKGformer/assets/166093595/eb53c948-df14-4060-82e1-b90f32f68866)

**Comment by njcx-ai** [comment]
您好，非常感谢您的关注。我们在MKG实验有pretrain实体embedding和link prediciton微调两个阶段，请问您的结果是否是基于完整步骤之后的嘛

**Comment by zxlzr** [comment]
请问您能提供问题细节吗

**Comment by zxlzr** [comment]
请问您的问题解决了吗 还有其他问题吗？
