### ISSUE TITLE
脚本问题

### ISSUE THREAD

**Issue by abcd171** [zjunlp/MKGformer#47]
![mmexport1718004537999](https://github.com/zjunlp/MKGformer/assets/172249000/8b88b1c4-528e-48a2-9f06-224509eecd69)
请问在运行这两个脚本文件时，我是使用Git运行的，出现的这个错误是什么原因呢

**Comment by njcx-ai** [comment]
您好，非常感谢你的关注。这个报错可能是是您环境配置问题或者shell脚本里有非法字符等等。

**Comment by abcd171** [comment]
你好，脚本我没有改动过，torch1.7.0对应的torchvision==0.8.0, dataclasses==0.6,其余的都和要求里的版本一样

**Comment by abcd171** [comment]
你好，我现在脚本运行完成，torch1.7.0对应的torchvision==0.8.0,dataclasses==0.6。其余版本都和要求里一样，下面的错误和这两个版本有关吗
![IMG_20240610_164653](https://github.com/zjunlp/MKGformer/assets/172249000/0be6d6ba-cc10-455c-8969-d9569c9140fc)
,dataclasses==0.6

**Comment by njcx-ai** [comment]
您好，感觉下面的错误跟transformer的库有关。

**Comment by zxlzr** [comment]
请问您的问题是否已解决，还有其他问题吗
