### ISSUE TITLE
Meet the problem when run the fb15k-237-image and wn18-images

### ISSUE THREAD

**Issue by Larry-Liu02** [zjunlp/MKGformer#48]
Dear authors,
I met this problem when I ran the MKG task. I tried to solve it in the data_module file, but I failed. Have you ever met the same problem?
warnings.warn(
Namespace(accelerator=None, accumulate_grad_batches=1, amp_backend='native', amp_level='O2', auto_lr_find=False, auto_scale_batch_size=False, auto_select_gpus=False, automatic_optimization=None, batch_size=64, bce=0, benchmark=False, check_val_every_n_epoch=1, checkpoint=None, checkpoint_callback=True, chunk='', data_class='KGC', data_dir='dataset/FB15k-237', dataset='./dataset/NELL', default_root_dir=None, deterministic=False, distributed_backend=None, enable_pl_optimizer=None, eval_batch_size=64, fast_dev_run=False, flush_logs_every_n_steps=100, gpus='0,', gradient_clip_val=0, label_smoothing=0.1, limit_predict_batches=1.0, limit_test_batches=1.0, limit_train_batches=1.0, limit_val_batches=1.0, litmodel_class='TransformerLitModel', log_every_n_steps=50, log_gpu_memory=None, logger=True, lr=0.0005, max_epochs=15, max_seq_length=64, max_steps=None, min_epochs=None, min_steps=None, model_class='UnimoKGC', model_name_or_path='bert-base-uncased', move_metrics_to_cpu=False, multiple_trainloader_mode='max_size_cycle', num_nodes=1, num_processes=1, num_sanity_val_steps=2, num_workers=4, optimizer='AdamW', overfit_batches=0.0, overwrite_cache=True, plugins=None, precision=32, prepare_data_per_node=True, pretrain=1, process_position=0, profiler=None, progress_bar_refresh_rate=None, reload_dataloaders_every_epoch=False, replace_sampler_ddp=True, resume_from_checkpoint=None, seed=7, stochastic_weight_avg=False, sync_batchnorm=False, task_name='fb15k-237', terminate_on_nan=False, tpu_cores=None, track_grad_norm=-1, truncated_bptt_steps=None, val_check_interval=1.0, wandb=False, warm_up_radio=0.1, weight_decay=0.01, weights_save_path=None, weights_summary='top')
Global seed set to 7
Load model state dict successful.
14951
unimo.text_embeddings.word_embeddings.weight
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
delete entities without text name.: 100%|█| 272115/272115 [00:00<00:00, 3973516.
total entity not in text : 0 
max number of filter entities : 4364 954
convert text to examples: 100%|████████| 14951/14951 [00:00<00:00, 87945.79it/s]
100%|███████████████████████████████████| 14951/14951 [00:02<00:00, 5994.50it/s]
delete entities without text name.: 100%|█| 17535/17535 [00:00<00:00, 2904245.80
total entity not in text : 0 
max number of filter entities : 4364 954
convert text to examples: 100%|████████| 14951/14951 [00:00<00:00, 85863.27it/s]
100%|███████████████████████████████████| 14951/14951 [00:02<00:00, 5965.58it/s]
delete entities without text name.: 100%|█| 20466/20466 [00:00<00:00, 2953910.04
total entity not in text : 0 
max number of filter entities : 4364 954
convert text to examples: 100%|███████| 14951/14951 [00:00<00:00, 554834.32it/s]
100%|███████████████████████████████████| 14951/14951 [00:02<00:00, 6126.98it/s]
LOCAL_RANK: 0 - CUDA_VISIBLE_DEVICES: [0]

  | Name    | Type                   | Params
---------------------------------------------------
0 | model   | UnimoKGC               | 237 M 
1 | loss_fn | LabelSmoothSoftmaxCEV1 | 0     
---------------------------------------------------
35.1 M    Trainable params
202 M     Non-trainable params
237 M     Total params
950.540   Total estimated model params size (MB)
Validation sanity check:  50%|██████████          | 1/2 [00:01<00:01,  1.37s/it]Traceback (most recent call last):
  File "main.py", line 152, in <module>
    main()
  File "main.py", line 134, in main
    trainer.fit(lit_model, datamodule=data)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 499, in fit
    self.dispatch()
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 546, in dispatch
    self.accelerator.start_training(self)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 73, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 114, in start_training
    self._results = trainer.run_train()
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 607, in run_train
    self.run_sanity_check(self.lightning_module)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 864, in run_sanity_check
    _, eval_results = self.run_evaluation(max_batches=self.num_sanity_val_batches)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 713, in run_evaluation
    for batch_idx, batch in enumerate(dataloader):
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 630, in __next__
    data = self._next_data()
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1325, in _next_data
    return self._process_data(data)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/_utils.py", line 694, in reraise
    raise exception
ValueError: Caught ValueError in DataLoader worker process 1.
Original Traceback (most recent call last):
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 54, in fetch
    return self.collate_fn(data)
  File "/media/kemove/16T/Jupyter/MKGformer/MKGformer/MKG/data/data_module.py", line 168, in __call__
    aux_img = aux_processor(images=aux_img, return_tensors='pt')['pixel_values'].squeeze()
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/models/clip/processing_clip.py", line 103, in __call__
    image_features = self.image_processor(images, return_tensors=return_tensors, **kwargs)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/image_processing_utils.py", line 494, in __call__
    return self.preprocess(images, **kwargs)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/models/clip/image_processing_clip.py", line 332, in preprocess
    images = [self.normalize(image=image, mean=image_mean, std=image_std) for image in images]
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/models/clip/image_processing_clip.py", line 332, in <listcomp>
    images = [self.normalize(image=image, mean=image_mean, std=image_std) for image in images]
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/models/clip/image_processing_clip.py", line 217, in normalize
    return normalize(image, mean=mean, std=std, data_format=data_format, **kwargs)
  File "/home/kemove/anaconda3/envs/MKG/lib/python3.8/site-packages/transformers/image_transforms.py", line 356, in normalize
    raise ValueError(f"mean must have {num_channels} elements if it is an iterable, got {len(mean)}")
ValueError: mean must have 1 elements if it is an iterable, got 3

**Comment by njcx-ai** [comment]
Thank you very much for your interest in our project. We have not encountered the same problem before. In this case, we suggest you double-check whether there might be any errors in the parameter passing.

**Comment by zxlzr** [comment]
hi, have you solved your issue yet?

**Comment by Larry-Liu02** [comment]
> hi, have you solved your issue yet?

Solved it due to the fb15k-237-image and wn18-images folders having some pure white and black images.

**Comment by zxlzr** [comment]
OK

**Comment by bjut-zhangdabao** [comment]
> > hi, have you solved your issue yet?
> 
> Solved it due to the fb15k-237-image and wn18-images folders having some pure white and black images.

Dear researcher,

I hope this message finds you well. Could you kindly share how you addressed the issue? I would greatly appreciate it if you could provide the solution. my Email：2569049998@qq.com

Thank you in advance. 
                                                                                                                                    bjut-zhangdabao
                                                                                                                                       2024.9.9

**Comment by njcx-ai** [comment]
There may be some extra pure white and black images that cause the inconsistent number.

**Comment by bjut-zhangdabao** [comment]
> There may be some extra pure white and black images that cause the inconsistent number.

Dear Scholar,

Hello, and thank you for your kind response. I would like to share some of my thoughts regarding this issue:

First of all, I am certain that there is no problem with the data. There are no purely white or black images in the dataset you provided, and all the images are RGB, which is great. After researching the cause of this issue for a few days, I concluded that it is related to the version of the transformers library. It seems that a bug, which hasn't been optimized in the newer versions of the transformers .

To address this issue, I offer two solutions:

1.Downgrade the Transformers library version, specifically to any version ≤ 4.24.0 (pip install transformers==4.19.0).
2.If you wish to use a higher version of the Transformers library, the solution is to replace and zero-pad the denormalized dimensions of the data processed by CLIP. I have also tried this method and found that it does not significantly affect the final result.                                                                                                     
![捕获1](https://github.com/user-attachments/assets/a1863904-8a86-453f-b79e-5cf98194171f)

Best regards,
bjut-zhangdaba

**Comment by njcx-ai** [comment]
The bug might have been caused by changes in the version of the transformers library. We sincerely appreciate your in-depth investigation of the issue and the valuable suggestions you have provided. We will adopt your recommendations and update the library version accordingly.

**Comment by bjut-zhangdabao** [comment]
> The bug might have been caused by changes in the version of the transformers library. We sincerely appreciate your in-depth investigation of the issue and the valuable suggestions you have provided. We will adopt your recommendations and update the library version accordingly.

I have learned a lot from this question as well. Thank you for your helpful response, and I sincerely hope that you achieve more innovation on your path in scientific research.
