### ISSUE TITLE
RobertaUseLabelWord求解为啥，还有用bash时会出现下面的问题

### ISSUE THREAD

**Issue by zjutnlper** [zjunlp/MKGformer#49]
Traceback (most recent call last):
  File "main.py", line 152, in <module>
    main()
  File "main.py", line 61, in main
    parser = _setup_parser()
  File "main.py", line 42, in _setup_parser
    model_class = _import_class(f"models.{temp_args.model_class}")
  File "main.py", line 16, in _import_class
    class_ = getattr(module, class_name)
AttributeError: module 'models' has no attribute 'RobertaUseLabelWord'
scripts/pretrain_fb15k-237-image.sh: line 2: --model_name_or_path: command not found
scripts/pretrain_fb15k-237-image.sh: line 3: --accumulate_grad_batches: command not found
scripts/pretrain_fb15k-237-image.sh: line 4: --model_class: command not found
scripts/pretrain_fb15k-237-image.sh: line 5: --batch_size: command not found
scripts/pretrain_fb15k-237-image.sh: line 6: --pretrain: command not found
scripts/pretrain_fb15k-237-image.sh: line 7: --bce: command not found
scripts/pretrain_fb15k-237-image.sh: line 8: --check_val_every_n_epoch: command not found
scripts/pretrain_fb15k-237-image.sh: line 9: --overwrite_cache: command not found
scripts/pretrain_fb15k-237-image.sh: line 10: --data_dir: command not found
scripts/pretrain_fb15k-237-image.sh: line 11: --task_name: command not found
scripts/pretrain_fb15k-237-image.sh: line 12: --eval_batch_size: command not found
scripts/pretrain_fb15k-237-image.sh: line 13: --max_seq_length: command not found
scripts/pretrain_fb15k-237-image.sh: line 14: --lr: command not found

**Comment by njcx-ai** [comment]
应该是bash的路径问题吧
