### ISSUE TITLE
请问一下，twitter2017的最优参数是？

### ISSUE THREAD

**Issue by ZihaoZheng98** [zjunlp/MKGformer#5]
我用仓库提供的默认参数，最高f1只能达到0.86? 论文中报的是0.8749

**Comment by njcx-ai** [comment]
您好，我们之前就是用默认参数跑是没问题的，这会正在用默认参数重跑核实下，稍后继续回复您的疑问。

**Comment by ZihaoZheng98** [comment]
> 您好，我们之前就是用默认参数跑是没问题的，这会正在用默认参数重跑核实下，稍后继续回复您的疑问。

多尝试了几个参数，已经达到论文中结果，非常感谢~

**Comment by 10652835** [comment]
> > 您好，我们之前就是用默认参数跑是没问题的，这会正在用默认参数重跑核实下，稍后继续回复您的疑问。
> 
> 多尝试了几个参数，已经达到论文中结果，非常感谢~

我也遇到了这个情况，你方便说一下你修改的参数吗

**Comment by Chenfeng1271** [comment]
> 

主要是环境问题（包括显卡），我在两台机子上结果不一致，不过我跑出来是87.39，还算正常。lr之类的超参基本是最优的。

**Comment by Nikol-coder** [comment]
> > 
> 
> 主要是环境问题（包括显卡），我在两台机子上结果不一致，不过我跑出来是87.39，还算正常。lr之类的超参基本是最优的。

您好，想向大家求教一下，在twitter2017上面做MNER任务，但是预测的实体全为pad 填充符号，损失为nan，想问下大家是否出现过这种问题？
![图片](https://github.com/user-attachments/assets/3adaafee-ff3e-4f1c-91a9-3518062f0e0d)

**Comment by Nikol-coder** [comment]
> > > 您好，我们之前就是用默认参数跑是没问题的，这会正在用默认参数重跑核实下，稍后继续回复您的疑问。
> > 
> > 
> > 多尝试了几个参数，已经达到论文中结果，非常感谢~
> 
> 我也遇到了这个情况，你方便说一下你修改的参数吗

您好，想向大家求教一下，在twitter2017上面做MNER任务，但是预测的实体全为pad 填充符号，损失为nan，想问下大家是否出现过这种问题？
![图片](https://github.com/user-attachments/assets/3adaafee-ff3e-4f1c-91a9-3518062f0e0d)
